<?php

/**
 * Implementation of hook_menu_default_menu_links().
 */
function primary_menu_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: primary-links:node/100
  $menu_links['primary-links:node/100'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/100',
    'router_path' => 'node/%',
    'link_title' => 'Bolig',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-49',
  );
  // Exported menu link: primary-links:node/1050
  $menu_links['primary-links:node/1050'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1050',
    'router_path' => 'node/%',
    'link_title' => 'Kantiner',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/86',
  );
  // Exported menu link: primary-links:node/1089
  $menu_links['primary-links:node/1089'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1089',
    'router_path' => 'node/%',
    'link_title' => 'Søknad',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/87',
  );
  // Exported menu link: primary-links:node/1090
  $menu_links['primary-links:node/1090'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1090',
    'router_path' => 'node/%',
    'link_title' => 'priser',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/87',
  );
  // Exported menu link: primary-links:node/1097
  $menu_links['primary-links:node/1097'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1097',
    'router_path' => 'node/%',
    'link_title' => 'Helse',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/98',
  );
  // Exported menu link: primary-links:node/1158
  $menu_links['primary-links:node/1158'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1158',
    'router_path' => 'node/%',
    'link_title' => 'timeplan',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/99',
  );
  // Exported menu link: primary-links:node/123
  $menu_links['primary-links:node/123'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/123',
    'router_path' => 'node/%',
    'link_title' => 'booking',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/99',
  );
  // Exported menu link: primary-links:node/1318
  $menu_links['primary-links:node/1318'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1318',
    'router_path' => 'node/%',
    'link_title' => 'Bokhandel',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: primary-links:node/1320
  $menu_links['primary-links:node/1320'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1320',
    'router_path' => 'node/%',
    'link_title' => 'Studenthus',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-45',
  );
  // Exported menu link: primary-links:node/63
  $menu_links['primary-links:node/63'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/63',
    'router_path' => 'node/%',
    'link_title' => 'studiestøtte',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/98',
  );
  // Exported menu link: primary-links:node/6483
  $menu_links['primary-links:node/6483'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/6483',
    'router_path' => 'node/%',
    'link_title' => 'Hybler',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/100',
  );
  // Exported menu link: primary-links:node/86
  $menu_links['primary-links:node/86'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/86',
    'router_path' => 'node/%',
    'link_title' => 'Mat & drikke',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-48',
  );
  // Exported menu link: primary-links:node/87
  $menu_links['primary-links:node/87'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/87',
    'router_path' => 'node/%',
    'link_title' => 'Barnehage',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-50',
  );
  // Exported menu link: primary-links:node/98
  $menu_links['primary-links:node/98'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/98',
    'router_path' => 'node/%',
    'link_title' => 'Rådgiving',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-46',
  );
  // Exported menu link: primary-links:node/99
  $menu_links['primary-links:node/99'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/99',
    'router_path' => 'node/%',
    'link_title' => 'Trening',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-47',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Barnehage');
  t('Bokhandel');
  t('Bolig');
  t('Helse');
  t('Hybler');
  t('Kantiner');
  t('Mat & drikke');
  t('Rådgiving');
  t('Studenthus');
  t('Søknad');
  t('Trening');
  t('booking');
  t('priser');
  t('studiestøtte');
  t('timeplan');


  return $menu_links;
}
