<?php
// $Id: exhibit_apachesolr.module,v 1.1 2009/01/28 22:32:54 arto Exp $

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implementation of hook_menu().
 */
function exhibit_apachesolr_menu() {
  return array(
    'exhibit/drupal/apachesolr_search/%' => array(
      'page callback'    => 'exhibit_apachesolr_get_search',
      'page arguments'   => array(3),
      'type'             => MENU_CALLBACK,
      'access arguments' => array('access exhibits'),
      'file'             => 'exhibit_apachesolr.pages.inc',
    ),
  );
}
